DECIMAL_MAX_DIGITS = 10
DECIMAL_PLACES = 5

SIMPLE_TRANSACTION = "simple_transaction"
CREDIT_TRANSACTION = "credit_transaction"
INVOICE_TRANSACTION = "invoice"

TYPE_OF_TRANSACTION = [SIMPLE_TRANSACTION, CREDIT_TRANSACTION, INVOICE_TRANSACTION]
TYPE_OF_TRANSACTION_CHOICES = tuple(zip(TYPE_OF_TRANSACTION, TYPE_OF_TRANSACTION))
ACCEPTABLE_TRANSACTION = [CREDIT_TRANSACTION, INVOICE_TRANSACTION]
CANCELABLE_TRANSACTION = []
