# Generated by Django 3.2.9 on 2021-12-05 14:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
    ]
