# Generated by Django 3.2.9 on 2021-12-05 17:04
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="request_id",
            field=models.CharField(
                max_length=128,
                null=True,
                unique=True,
                verbose_name="Client side random unique random value",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="type_of_transaction",
            field=models.CharField(
                choices=[
                    ("simple_transaction", "simple_transaction"),
                    ("credit_transaction", "credit_transaction"),
                    ("invoice", "invoice"),
                ],
                default="simple_transaction",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
