# Generated by Django 3.2.9 on 2021-12-05 17:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_auto_20211205_1704"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="processed",
            field=models.BooleanField(
                default=False, verbose_name="Transaction WAS processed"
            ),
        ),
    ]
