# Generated by Django 3.2.9 on 2021-12-06 07:53
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0003_transaction_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="canceled",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Transaction CANCELED"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
